[package]
name = "lifx-web"
version = "0.1.0"
authors = ["Todd Taomae <ttaomae@gmail.com>"]
edition = "2018"

[dependencies]
lifx-client = { path = "../lifx-client" }
rocket = "0.4.5"
rocket_contrib = "0.4.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5.6"
